version: '3.7'

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9093:9093"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENER: INSIDE_KAFKA:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_NAME_INTERNAL: INSIDE_KAFKA
      KAFKA_LISTENER_PORT: 9093
      KAFKA_LISTENER_NAMES: INSIDE_KAFKA
      KAFKA_LISTENER_INTERNAL: INSIDE_KAFKA
      KAFKA_LISTENER_INTERNAL_PORT: 9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_INTERNAL_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_ADVERTISED_LISTENER: INSIDE_KAFKA
      KAFKA_LISTENER_NAME_INTERNAL: INSIDE_KAFKA
      KAFKA_LISTENER_PORT: 9093
      KAFKA_LISTENER_NAMES: INSIDE_KAFKA
      KAFKA_LISTENER_INTERNAL: INSIDE_KAFKA
      KAFKA_LISTENER_INTERNAL_PORT: 9093
