name: Build and Deploy on Release

on:
  release:
    types: [published, edited]

env:
  IMAGE_NAME: quynd17/cprms-be
  IMAGE_TAG: ${{ github.ref_name }}
  APP_NAME: cprms-be
  RG: cprms
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker image
        run: |
          cd platform/src/CPRMS.BE
          docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

      - name: Push Docker image
        run: docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

  deploy:
    name: Deploy to Azure Container Apps
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to ACA
        uses: azure/container-apps-deploy-action@v1
        with:
          appName: ${{env.APP_NAME}}
          resourceGroup: ${{env.RG}}
          image: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
