name: Build and Push Docker image

on:
  push:
    branches: [test-deploy] 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker image
        run: |
          cd platform/src/CPRMS.BE
          docker build -t quynd17/cprms-be .

      - name: Push Docker image
        run: |
          docker push quynd17/cprms-be
